/**
 * Mock account data for Maria's persona
 * 32yo in NYC, 6 accounts totaling ~$23K
 */

import type { Account } from '@vindicate/shared';

// Generate consistent IDs for cross-referencing
export const ACCOUNT_IDS = {
  nyuMedical: 'acc-001-nyu-medical',
  capitalOne: 'acc-002-capital-one',
  synchrony: 'acc-003-synchrony',
  conEdison: 'acc-004-con-edison',
  discoveryPersonal: 'acc-005-discovery-personal',
  mtSinaiMedical: 'acc-006-mt-sinai',
  chaseSapphire: 'acc-007-chase',
  macys: 'acc-008-macys',
} as const;

export const mockAccounts: Account[] = [
  // Account 1: NYU Langone Medical - In Collections, large balance
  {
    id: ACCOUNT_IDS.nyuMedical,
    creditorName: 'NYU Langone Health',
    collectorName: 'IC System Inc.',
    accountNumber: 'NYU-2024-78543',
    creditorPhone: '888-524-0010',
    creditorAddress: '550 1st Avenue, New York, NY 10016',
    originalBalance: 8750,
    currentBalance: 8750,
    status: 'in-collections',
    statusHistory: [
      {
        from: 'current',
        to: 'late',
        date: '2025-03-15',
        reason: 'Missed payment after insurance denial',
      },
      {
        from: 'late',
        to: 'in-collections',
        date: '2025-06-01',
        reason: 'Account sold to IC System',
      },
    ],
    dateOpened: '2024-11-20',
    dateOfLastActivity: '2026-01-28',
    dateAddedToApp: '2026-01-15',
    statuteOfLimitationsDate: '2031-06-01',
    statuteOfLimitationsState: 'NY',
    category: 'medical',
    tags: ['emergency-room', 'insurance-denied'],
    notes: 'ER visit for appendicitis. Insurance denied coverage claiming pre-existing condition.',
    activityIds: ['act-001', 'act-002', 'act-009'],
    caseIds: ['case-001'],
    documentIds: [],
    importSource: 'manual',
    creditBureaus: ['equifax', 'experian', 'transunion'],
    createdAt: '2026-01-15T10:30:00Z',
    updatedAt: '2026-02-01T14:22:00Z',
  },

  // Account 2: Capital One Credit Card - Payment Plan
  {
    id: ACCOUNT_IDS.capitalOne,
    creditorName: 'Capital One',
    accountNumber: '****4521',
    creditorPhone: '800-955-7070',
    creditorAddress: 'P.O. Box 30285, Salt Lake City, UT 84130',
    originalBalance: 4200,
    currentBalance: 3150,
    interestRate: 0, // Frozen during payment plan
    minimumPayment: 175,
    status: 'payment-plan',
    statusHistory: [
      {
        from: 'current',
        to: 'late',
        date: '2025-02-01',
        reason: 'Reduced work hours during illness',
      },
      {
        from: 'late',
        to: 'charged-off',
        date: '2025-08-01',
        reason: 'Account charged off after 180 days',
      },
      {
        from: 'charged-off',
        to: 'payment-plan',
        date: '2025-10-15',
        reason: 'Negotiated hardship payment plan',
      },
    ],
    dateOpened: '2021-06-15',
    dateOfLastActivity: '2026-02-01',
    dateAddedToApp: '2026-01-15',
    statuteOfLimitationsDate: '2031-08-01',
    statuteOfLimitationsState: 'NY',
    category: 'credit-card',
    tags: ['hardship-plan', 'making-progress'],
    notes: 'Negotiated 0% interest hardship plan. $175/month for 18 months.',
    activityIds: ['act-003', 'act-004', 'act-010'],
    caseIds: [],
    documentIds: [],
    paymentPlanId: 'pp-001',
    importSource: 'credit-report',
    creditBureaus: ['equifax', 'experian', 'transunion'],
    createdAt: '2026-01-15T10:35:00Z',
    updatedAt: '2026-02-01T09:00:00Z',
  },

  // Account 3: Synchrony/Amazon Store Card - Disputed
  {
    id: ACCOUNT_IDS.synchrony,
    creditorName: 'Synchrony Bank',
    collectorName: 'Portfolio Recovery Associates',
    accountNumber: 'SY-7890-XXXX',
    creditorPhone: '866-419-4096',
    originalBalance: 2340,
    currentBalance: 2890, // Fees added
    status: 'disputed',
    statusHistory: [
      {
        from: 'current',
        to: 'in-collections',
        date: '2025-04-10',
      },
      {
        from: 'in-collections',
        to: 'disputed',
        date: '2026-01-20',
        reason: 'Filed dispute - incorrect balance and fees',
      },
    ],
    dateOpened: '2022-11-25',
    dateOfLastActivity: '2026-01-25',
    dateAddedToApp: '2026-01-15',
    statuteOfLimitationsDate: '2031-04-10',
    statuteOfLimitationsState: 'NY',
    category: 'credit-card',
    tags: ['store-card', 'dispute-pending'],
    notes: 'Disputed due to incorrect fees and balance. Original card was Amazon store card.',
    activityIds: ['act-005', 'act-011'],
    caseIds: ['case-002'],
    documentIds: [],
    importSource: 'credit-report',
    creditBureaus: ['equifax', 'transunion'],
    createdAt: '2026-01-15T10:40:00Z',
    updatedAt: '2026-01-25T16:00:00Z',
  },

  // Account 4: Con Edison - Settled
  {
    id: ACCOUNT_IDS.conEdison,
    creditorName: 'Consolidated Edison',
    accountNumber: 'CE-NYC-445566',
    creditorPhone: '800-752-6633',
    creditorAddress: '4 Irving Place, New York, NY 10003',
    originalBalance: 890,
    currentBalance: 0,
    status: 'settled',
    statusHistory: [
      {
        from: 'current',
        to: 'late',
        date: '2025-01-15',
      },
      {
        from: 'late',
        to: 'in-collections',
        date: '2025-04-01',
      },
      {
        from: 'in-collections',
        to: 'settled',
        date: '2025-12-20',
        reason: 'Settled for 60% of balance',
      },
    ],
    dateOpened: '2023-03-01',
    dateOfLastActivity: '2025-12-20',
    dateAddedToApp: '2026-01-15',
    category: 'utility',
    tags: ['settled', 'success'],
    notes: 'Settled for $534 (60%). First account resolved!',
    activityIds: ['act-006'],
    caseIds: [],
    documentIds: [],
    importSource: 'manual',
    creditBureaus: ['equifax'],
    createdAt: '2026-01-15T10:45:00Z',
    updatedAt: '2025-12-20T11:30:00Z',
  },

  // Account 5: Discover Personal Loan - In Collections with harassment
  {
    id: ACCOUNT_IDS.discoveryPersonal,
    creditorName: 'Discover Personal Loans',
    collectorName: 'Midland Credit Management',
    accountNumber: 'DPL-89012',
    creditorPhone: '800-347-0434',
    originalBalance: 5000,
    currentBalance: 5650,
    interestRate: 18.99,
    status: 'in-collections',
    statusHistory: [
      {
        from: 'current',
        to: 'late',
        date: '2025-05-01',
      },
      {
        from: 'late',
        to: 'charged-off',
        date: '2025-11-01',
      },
      {
        from: 'charged-off',
        to: 'in-collections',
        date: '2025-12-15',
        reason: 'Sold to Midland Credit',
      },
    ],
    dateOpened: '2023-08-10',
    dateOfLastActivity: '2026-02-05',
    dateAddedToApp: '2026-01-15',
    statuteOfLimitationsDate: '2031-11-01',
    statuteOfLimitationsState: 'NY',
    category: 'personal-loan',
    tags: ['harassment', 'fdcpa-violation'],
    notes: 'Midland has called multiple times outside allowed hours. Documenting for FDCPA complaint.',
    activityIds: ['act-007', 'act-008', 'act-012', 'act-013'],
    caseIds: [],
    documentIds: [],
    importSource: 'credit-report',
    creditBureaus: ['equifax', 'experian', 'transunion'],
    createdAt: '2026-01-15T10:50:00Z',
    updatedAt: '2026-02-05T08:15:00Z',
  },

  // Account 6: Mt. Sinai Medical - Recent, small balance
  {
    id: ACCOUNT_IDS.mtSinaiMedical,
    creditorName: 'Mount Sinai Health System',
    accountNumber: 'MS-2025-11234',
    creditorPhone: '212-659-8500',
    creditorAddress: '1 Gustave L. Levy Place, New York, NY 10029',
    originalBalance: 1250,
    currentBalance: 1250,
    status: 'late',
    statusHistory: [
      {
        from: 'current',
        to: 'late',
        date: '2026-01-15',
        reason: 'Waiting for insurance to process',
      },
    ],
    dateOpened: '2025-10-05',
    dateOfLastActivity: '2026-01-28',
    dateAddedToApp: '2026-01-20',
    category: 'medical',
    tags: ['insurance-pending', 'recent'],
    notes: 'Follow-up visit. Insurance claim still processing. May be partially covered.',
    activityIds: ['act-014'],
    caseIds: [],
    documentIds: [],
    importSource: 'manual',
    creditBureaus: [],
    createdAt: '2026-01-20T09:00:00Z',
    updatedAt: '2026-01-28T14:00:00Z',
  },

  // Account 7: Chase Sapphire - Current (Good standing example)
  {
    id: ACCOUNT_IDS.chaseSapphire,
    creditorName: 'Chase Bank',
    accountNumber: '****7890',
    creditorPhone: '800-432-3117',
    originalBalance: 0,
    currentBalance: 450, // Normal usage
    minimumPayment: 25,
    status: 'current',
    statusHistory: [],
    dateOpened: '2020-03-15',
    dateOfLastActivity: '2026-02-01',
    dateAddedToApp: '2026-01-15',
    category: 'credit-card',
    tags: ['good-standing', 'active'],
    notes: 'Only card in good standing. Using for small purchases to maintain credit history.',
    activityIds: [],
    caseIds: [],
    documentIds: [],
    importSource: 'manual',
    creditBureaus: ['equifax', 'experian', 'transunion'],
    createdAt: '2026-01-15T11:00:00Z',
    updatedAt: '2026-02-01T10:00:00Z',
  },

  // Account 8: Macy's Store Card - Charged Off
  {
    id: ACCOUNT_IDS.macys,
    creditorName: "Macy's",
    collectorName: 'Citibank Retail Services',
    accountNumber: 'MACYS-XXXX-8901',
    originalBalance: 1100,
    currentBalance: 1320, // With fees
    status: 'charged-off',
    statusHistory: [
      {
        from: 'current',
        to: 'late',
        date: '2025-02-28',
      },
      {
        from: 'late',
        to: 'charged-off',
        date: '2025-09-01',
      },
    ],
    dateOpened: '2022-08-20',
    dateOfLastActivity: '2025-11-10',
    dateAddedToApp: '2026-01-15',
    statuteOfLimitationsDate: '2031-09-01',
    statuteOfLimitationsState: 'NY',
    category: 'credit-card',
    tags: ['store-card', 'charged-off'],
    notes: 'Low priority. Considering debt validation letter.',
    activityIds: ['act-015'],
    caseIds: [],
    documentIds: [],
    importSource: 'credit-report',
    creditBureaus: ['experian', 'transunion'],
    createdAt: '2026-01-15T11:05:00Z',
    updatedAt: '2025-11-10T09:00:00Z',
  },
];

// Computed totals for Maria's dashboard
export const mockAccountsSummary = {
  totalOriginalDebt: mockAccounts.reduce((sum, acc) => sum + acc.originalBalance, 0),
  totalCurrentDebt: mockAccounts.reduce((sum, acc) => sum + acc.currentBalance, 0),
  accountCount: mockAccounts.length,
  inCollectionsCount: mockAccounts.filter(acc => acc.status === 'in-collections').length,
  disputedCount: mockAccounts.filter(acc => acc.status === 'disputed').length,
  settledCount: mockAccounts.filter(acc => acc.status === 'settled').length,
  paymentPlanCount: mockAccounts.filter(acc => acc.status === 'payment-plan').length,
};
