/**
 * Application constants for Vindicate NYC
 */

export const APP_NAME = 'Vindicate NYC';
export const APP_VERSION = '0.1.0';

/**
 * Data classification tiers
 */
export const DataTier = {
  TIER_1_HIGHEST: 1, // SSN, bank accounts, tax docs
  TIER_2_HIGH: 2,    // Income, credit reports
  TIER_3_MEDIUM: 3,  // Case narrative, timeline
  TIER_4_LOW: 4,     // Templates, metrics
} as const;

/**
 * IRS standards version
 */
export const IRS_STANDARDS_VERSION = '2025-Q1';

/**
 * Supported states (starting with NY)
 */
export const SUPPORTED_STATES = ['NY'] as const;

/**
 * Legal disclaimers
 */
export const DISCLAIMERS = {
  GENERAL: `DISCLAIMER: This information is provided for educational and informational
purposes only. This is not legal advice. Consult with a licensed attorney before
taking any legal action.`,

  AI_GENERATED: `This content was generated by an AI system. While we strive for accuracy,
AI-generated content should be reviewed carefully and verified before use in any
legal proceeding.`,

  FINANCIAL: `Financial calculations are estimates based on IRS National Standards and
user-provided information. Actual results may vary. Consult a tax professional for
personalized advice.`,
} as const;
